// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo.proto
// Protobuf Java Version: 4.28.2

package todoPackage;

public final class TodoOuterClass {
  private TodoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      TodoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TodoItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:todoPackage.TodoItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code todoPackage.TodoItem}
   */
  public static final class TodoItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:todoPackage.TodoItem)
      TodoItemOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        TodoItem.class.getName());
    }
    // Use TodoItem.newBuilder() to construct.
    private TodoItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TodoItem() {
      text_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              todoPackage.TodoOuterClass.TodoItem.class, todoPackage.TodoOuterClass.TodoItem.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, text_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof todoPackage.TodoOuterClass.TodoItem)) {
        return super.equals(obj);
      }
      todoPackage.TodoOuterClass.TodoItem other = (todoPackage.TodoOuterClass.TodoItem) obj;

      if (getId()
          != other.getId()) return false;
      if (!getText()
          .equals(other.getText())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static todoPackage.TodoOuterClass.TodoItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static todoPackage.TodoOuterClass.TodoItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static todoPackage.TodoOuterClass.TodoItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(todoPackage.TodoOuterClass.TodoItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code todoPackage.TodoItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:todoPackage.TodoItem)
        todoPackage.TodoOuterClass.TodoItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                todoPackage.TodoOuterClass.TodoItem.class, todoPackage.TodoOuterClass.TodoItem.Builder.class);
      }

      // Construct using todoPackage.TodoOuterClass.TodoItem.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        text_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItem_descriptor;
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.TodoItem getDefaultInstanceForType() {
        return todoPackage.TodoOuterClass.TodoItem.getDefaultInstance();
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.TodoItem build() {
        todoPackage.TodoOuterClass.TodoItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.TodoItem buildPartial() {
        todoPackage.TodoOuterClass.TodoItem result = new todoPackage.TodoOuterClass.TodoItem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(todoPackage.TodoOuterClass.TodoItem result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.text_ = text_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof todoPackage.TodoOuterClass.TodoItem) {
          return mergeFrom((todoPackage.TodoOuterClass.TodoItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(todoPackage.TodoOuterClass.TodoItem other) {
        if (other == todoPackage.TodoOuterClass.TodoItem.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 2;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:todoPackage.TodoItem)
    }

    // @@protoc_insertion_point(class_scope:todoPackage.TodoItem)
    private static final todoPackage.TodoOuterClass.TodoItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new todoPackage.TodoOuterClass.TodoItem();
    }

    public static todoPackage.TodoOuterClass.TodoItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TodoItem>
        PARSER = new com.google.protobuf.AbstractParser<TodoItem>() {
      @java.lang.Override
      public TodoItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TodoItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TodoItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public todoPackage.TodoOuterClass.TodoItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TodoItemsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:todoPackage.TodoItems)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    java.util.List<todoPackage.TodoOuterClass.TodoItem> 
        getItemsList();
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    todoPackage.TodoOuterClass.TodoItem getItems(int index);
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    java.util.List<? extends todoPackage.TodoOuterClass.TodoItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    todoPackage.TodoOuterClass.TodoItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code todoPackage.TodoItems}
   */
  public static final class TodoItems extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:todoPackage.TodoItems)
      TodoItemsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        TodoItems.class.getName());
    }
    // Use TodoItems.newBuilder() to construct.
    private TodoItems(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TodoItems() {
      items_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItems_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              todoPackage.TodoOuterClass.TodoItems.class, todoPackage.TodoOuterClass.TodoItems.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<todoPackage.TodoOuterClass.TodoItem> items_;
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<todoPackage.TodoOuterClass.TodoItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends todoPackage.TodoOuterClass.TodoItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    @java.lang.Override
    public todoPackage.TodoOuterClass.TodoItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .todoPackage.TodoItem items = 1;</code>
     */
    @java.lang.Override
    public todoPackage.TodoOuterClass.TodoItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof todoPackage.TodoOuterClass.TodoItems)) {
        return super.equals(obj);
      }
      todoPackage.TodoOuterClass.TodoItems other = (todoPackage.TodoOuterClass.TodoItems) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static todoPackage.TodoOuterClass.TodoItems parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static todoPackage.TodoOuterClass.TodoItems parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static todoPackage.TodoOuterClass.TodoItems parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(todoPackage.TodoOuterClass.TodoItems prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code todoPackage.TodoItems}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:todoPackage.TodoItems)
        todoPackage.TodoOuterClass.TodoItemsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItems_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItems_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                todoPackage.TodoOuterClass.TodoItems.class, todoPackage.TodoOuterClass.TodoItems.Builder.class);
      }

      // Construct using todoPackage.TodoOuterClass.TodoItems.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_TodoItems_descriptor;
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.TodoItems getDefaultInstanceForType() {
        return todoPackage.TodoOuterClass.TodoItems.getDefaultInstance();
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.TodoItems build() {
        todoPackage.TodoOuterClass.TodoItems result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.TodoItems buildPartial() {
        todoPackage.TodoOuterClass.TodoItems result = new todoPackage.TodoOuterClass.TodoItems(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(todoPackage.TodoOuterClass.TodoItems result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(todoPackage.TodoOuterClass.TodoItems result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof todoPackage.TodoOuterClass.TodoItems) {
          return mergeFrom((todoPackage.TodoOuterClass.TodoItems)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(todoPackage.TodoOuterClass.TodoItems other) {
        if (other == todoPackage.TodoOuterClass.TodoItems.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                todoPackage.TodoOuterClass.TodoItem m =
                    input.readMessage(
                        todoPackage.TodoOuterClass.TodoItem.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<todoPackage.TodoOuterClass.TodoItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<todoPackage.TodoOuterClass.TodoItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          todoPackage.TodoOuterClass.TodoItem, todoPackage.TodoOuterClass.TodoItem.Builder, todoPackage.TodoOuterClass.TodoItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public java.util.List<todoPackage.TodoOuterClass.TodoItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public todoPackage.TodoOuterClass.TodoItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder setItems(
          int index, todoPackage.TodoOuterClass.TodoItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder setItems(
          int index, todoPackage.TodoOuterClass.TodoItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder addItems(todoPackage.TodoOuterClass.TodoItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder addItems(
          int index, todoPackage.TodoOuterClass.TodoItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder addItems(
          todoPackage.TodoOuterClass.TodoItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder addItems(
          int index, todoPackage.TodoOuterClass.TodoItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends todoPackage.TodoOuterClass.TodoItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public todoPackage.TodoOuterClass.TodoItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public todoPackage.TodoOuterClass.TodoItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public java.util.List<? extends todoPackage.TodoOuterClass.TodoItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public todoPackage.TodoOuterClass.TodoItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            todoPackage.TodoOuterClass.TodoItem.getDefaultInstance());
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public todoPackage.TodoOuterClass.TodoItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, todoPackage.TodoOuterClass.TodoItem.getDefaultInstance());
      }
      /**
       * <code>repeated .todoPackage.TodoItem items = 1;</code>
       */
      public java.util.List<todoPackage.TodoOuterClass.TodoItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          todoPackage.TodoOuterClass.TodoItem, todoPackage.TodoOuterClass.TodoItem.Builder, todoPackage.TodoOuterClass.TodoItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              todoPackage.TodoOuterClass.TodoItem, todoPackage.TodoOuterClass.TodoItem.Builder, todoPackage.TodoOuterClass.TodoItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:todoPackage.TodoItems)
    }

    // @@protoc_insertion_point(class_scope:todoPackage.TodoItems)
    private static final todoPackage.TodoOuterClass.TodoItems DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new todoPackage.TodoOuterClass.TodoItems();
    }

    public static todoPackage.TodoOuterClass.TodoItems getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TodoItems>
        PARSER = new com.google.protobuf.AbstractParser<TodoItems>() {
      @java.lang.Override
      public TodoItems parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TodoItems> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TodoItems> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public todoPackage.TodoOuterClass.TodoItems getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface voidNoParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:todoPackage.voidNoParam)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code todoPackage.voidNoParam}
   */
  public static final class voidNoParam extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:todoPackage.voidNoParam)
      voidNoParamOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        voidNoParam.class.getName());
    }
    // Use voidNoParam.newBuilder() to construct.
    private voidNoParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private voidNoParam() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return todoPackage.TodoOuterClass.internal_static_todoPackage_voidNoParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return todoPackage.TodoOuterClass.internal_static_todoPackage_voidNoParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              todoPackage.TodoOuterClass.voidNoParam.class, todoPackage.TodoOuterClass.voidNoParam.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof todoPackage.TodoOuterClass.voidNoParam)) {
        return super.equals(obj);
      }
      todoPackage.TodoOuterClass.voidNoParam other = (todoPackage.TodoOuterClass.voidNoParam) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static todoPackage.TodoOuterClass.voidNoParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static todoPackage.TodoOuterClass.voidNoParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static todoPackage.TodoOuterClass.voidNoParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(todoPackage.TodoOuterClass.voidNoParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code todoPackage.voidNoParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:todoPackage.voidNoParam)
        todoPackage.TodoOuterClass.voidNoParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_voidNoParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_voidNoParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                todoPackage.TodoOuterClass.voidNoParam.class, todoPackage.TodoOuterClass.voidNoParam.Builder.class);
      }

      // Construct using todoPackage.TodoOuterClass.voidNoParam.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return todoPackage.TodoOuterClass.internal_static_todoPackage_voidNoParam_descriptor;
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.voidNoParam getDefaultInstanceForType() {
        return todoPackage.TodoOuterClass.voidNoParam.getDefaultInstance();
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.voidNoParam build() {
        todoPackage.TodoOuterClass.voidNoParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public todoPackage.TodoOuterClass.voidNoParam buildPartial() {
        todoPackage.TodoOuterClass.voidNoParam result = new todoPackage.TodoOuterClass.voidNoParam(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof todoPackage.TodoOuterClass.voidNoParam) {
          return mergeFrom((todoPackage.TodoOuterClass.voidNoParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(todoPackage.TodoOuterClass.voidNoParam other) {
        if (other == todoPackage.TodoOuterClass.voidNoParam.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:todoPackage.voidNoParam)
    }

    // @@protoc_insertion_point(class_scope:todoPackage.voidNoParam)
    private static final todoPackage.TodoOuterClass.voidNoParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new todoPackage.TodoOuterClass.voidNoParam();
    }

    public static todoPackage.TodoOuterClass.voidNoParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<voidNoParam>
        PARSER = new com.google.protobuf.AbstractParser<voidNoParam>() {
      @java.lang.Override
      public voidNoParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<voidNoParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<voidNoParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public todoPackage.TodoOuterClass.voidNoParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todoPackage_TodoItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todoPackage_TodoItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todoPackage_TodoItems_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todoPackage_TodoItems_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todoPackage_voidNoParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todoPackage_voidNoParam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntodo.proto\022\013todoPackage\"$\n\010TodoItem\022\n\n" +
      "\002id\030\001 \001(\005\022\014\n\004text\030\002 \001(\t\"1\n\tTodoItems\022$\n\005" +
      "items\030\001 \003(\0132\025.todoPackage.TodoItem\"\r\n\013vo" +
      "idNoParam2\306\001\n\004Todo\022:\n\ncreateTodo\022\025.todoP" +
      "ackage.TodoItem\032\025.todoPackage.TodoItem\022<" +
      "\n\010getTodos\022\030.todoPackage.voidNoParam\032\026.t" +
      "odoPackage.TodoItems\022D\n\016getTodosStream\022\030" +
      ".todoPackage.voidNoParam\032\026.todoPackage.T" +
      "odoItems0\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_todoPackage_TodoItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_todoPackage_TodoItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todoPackage_TodoItem_descriptor,
        new java.lang.String[] { "Id", "Text", });
    internal_static_todoPackage_TodoItems_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_todoPackage_TodoItems_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todoPackage_TodoItems_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_todoPackage_voidNoParam_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_todoPackage_voidNoParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todoPackage_voidNoParam_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
